### ISSUE TITLE
Internet host can be left empty when ports are assigned

### ISSUE THREAD

**Issue by Vafa-Andalibi** [iot-onboarding/mudmaker#5]
**Issue**: 
The generated JSON would be invalid

**How to Reproduce**:
Generate a mud-file with internet access , specify a port but leave the host field empty and mudmaker will not disallow this. 

I used an online JSON validator like [this](https://jsonlint.com/) and noticed that an extra comma in "matched" is causing the issue (line 5 in example below): 

```
"matches": {
    "ipv4": {
        "ietf-acldns:src-dnsname": "www.google.com",
        "protocol": 6
     },
},
```

**Comment by Vafa-Andalibi** [comment]
This might be an error on my side, I'm doing further testing. Will close it for now

**Comment by Vafa-Andalibi** [comment]
Updated: the main issue is that mudmaker allows the "internet host" field to be left empty and the resulted json would be invalid.

**Comment by elear** [comment]
I think this problem is either fixed or I can't reproduce it.

**Comment by Vafa-Andalibi** [comment]
I checked and this is fixed.
